name: Build binaries for Linux & Windows
on: workflow_dispatch

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install -r requirements-dev.txt
          python -m PyInstaller -F pyinstxtractor-ng.py

      - name: Set release date
        run: echo "RELEASE_DATE=$(date -u +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_DATE }}
          tag:  ${{ env.RELEASE_DATE }}
          artifacts: "dist/pyinstxtractor-ng"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: true


  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: |
          python -m pip install -r requirements-dev.txt
          python -m PyInstaller -F pyinstxtractor-ng.py

      - name: Set release date
        shell: bash
        run: echo "RELEASE_DATE=$(date -u +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.RELEASE_DATE }}
          tag:  ${{ env.RELEASE_DATE }}
          artifacts: "dist/pyinstxtractor-ng.exe"
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          draft: true